=== drogatkin/7Bee/bee.dtd
<!-- $Id: bee.dtd,v 1.34 2011/06/28 23:23:36 dmitriy Exp $
  project Bee, DTD file of bee make files 
  Copyright (c) 2004 Dmitriy Rogatkin   -->

<!ENTITY % PROJ_TYPE "build|test|run">

<!ENTITY % VAR_TYPE "variable|file|directory|url|number|date|array|path|environment|property">
<!ENTITY % BLOCK_TYPE "then|else|case">
<!ENTITY % YES_NO "yes|no">

<!ELEMENT bee (variable|expression|block|target+)*>
<!ATTLIST bee
         name    CDATA #REQUIRED
         dir     CDATA #IMPLIED
         type    (%PROJ_TYPE;) "build"
>

<!ELEMENT variable (#PCDATA)>

<!ATTLIST variable
         name    CDATA #REQUIRED
         type (%VAR_TYPE;) #IMPLIED
>

<!ELEMENT expression (operator|for|function|if|switch)>
<!-- name - the result expression is stored
     variable - alias of name -->
<!ATTLIST expression
         name    CDATA #REQUIRED
         variable CDATA #IMPLIED
>

<!ELEMENT operator (value|function|variable|expression|operator)*>
<!ATTLIST operator
         name    CDATA #REQUIRED
         type (%VAR_TYPE;) #IMPLIED
>

<!ELEMENT value (#PCDATA)>
<!ATTLIST value
         name CDATA        #IMPLIED
         type (%VAR_TYPE;) #IMPLIED
         variable CDATA    #IMPLIED
         property CDATA    #IMPLIED
>

<!ELEMENT function (parameter*)>
<!ATTLIST function
         name    CDATA #REQUIRED
>

<!ELEMENT parameter (#PCDATA|expression|function|operator)*>
<!ATTLIST parameter
         name    CDATA #IMPLIED
         variable CDATA #IMPLIED
         value CDATA #IMPLIED
         type (%VAR_TYPE;) #IMPLIED
>

<!ELEMENT target (dependency*, (block|task)*, echo*)>
<!ATTLIST target
         name CDATA #REQUIRED
         dir CDATA #IMPLIED
         comment CDATA #IMPLIED
>

<!ELEMENT echo (#PCDATA)>
<!-- attribute options is similar to options for Unix echo
       -n     do not output the trailing newline
       -e     enable interpretation of the backslash-escaped characters listed below
       -E     disable interpretation of those sequences in STRINGs
       Without -E, the following sequences are recognized and interpolated:
       \NNN   the character whose ASCII code is NNN (octal)
       \\     backslash
       \a     alert (BEL)
       \b     backspace
       \c     suppress trailing newline
       \f     form feed
       \n     new line
       \r     carriage return
       \t     horizontal tab
       \v     vertical tab
-->
<!ATTLIST echo
         variable CDATA        #IMPLIED
         name     CDATA        #IMPLIED
         type     (%VAR_TYPE;) #IMPLIED
         options  CDATA        #IMPLIED
>

<!ELEMENT for (task|operator|expression|block|interrupt|if)*>
<!ATTLIST for
         variable CDATA #REQUIRED
         in CDATA #REQUIRED 
         separator CDATA #IMPLIED
>

<!ELEMENT task (parameter*, (onexit?,onexception?))>

<!ATTLIST task
         name  CDATA #REQUIRED
         code  CDATA #IMPLIED
         exec  CDATA #IMPLIED
         path  CDATA #IMPLIED
         dir   CDATA #IMPLIED
         stdout CDATA #IMPLIED
         stdin CDATA #IMPLIED
         errout CDATA #IMPLIED
>

<!ELEMENT onexit (if)>

<!ELEMENT onexception (block)>

<!ELEMENT if (expression, (then|block), (else|block)?)>

<!ELEMENT then (task|function|expression|echo|if|for|switch|interrupt)*>

<!ELEMENT else (task|function|expression|echo|if|for|switch|interrupt)*>

<!ELEMENT block (task|function|expression|echo|if|for|switch|interrupt)*>
<!ATTLIST block
          name CDATA #IMPLIED
          variable CDATA #IMPLIED
          value CDATA #IMPLIED
          type (%BLOCK_TYPE;) #IMPLIED
>

<!ELEMENT switch (expression, (block)*)>
<!ATTLIST switch
          name CDATA #IMPLIED
          variable CDATA #IMPLIED
>

<!ELEMENT dependency (#PCDATA|expression|function|operator)*>
<!-- name - variable name where result of dependency calculation stored
     target - target of dependency
     variable - name of variable it depend on, can be boolean
-->
<!ATTLIST dependency
          name CDATA #IMPLIED
          target CDATA #IMPLIED
          variable CDATA #IMPLIED
          process_only (%YES_NO;) "no" 
>

<!ELEMENT interrupt (empty)>
<!-- name - can be a name of named block to unterrupt 
-->
<!ATTLIST interrupt
          name CDATA #IMPLIED
>

=== drogatkin/7Bee/examples/generic/bee-hivol.xml
<?xml version="1.0" encoding="utf-8"?>
 <!DOCTYPE bee PUBLIC "-//Dmitriy Rogatkin//DTD Bee Project Builder 1.0//EN"
    "https://raw.githubusercontent.com/drogatkin/7Bee/master/bee.dtd" [
      <!ENTITY env SYSTEM "./env.xml">
      <!ENTITY project "project name">
      <!ENTITY build_directory "your build directory">
      <!ENTITY source_directory "src"> <!-- change if differs -->
      <!ENTITY build_file "your jar.jar">
      <!ENTITY domain "com">
      <!ENTITY manifestf "type relative path to manifest">
      <!ENTITY main_class "type main class for run">
      ]>
<!-- $Id: bee-hivol.xml,v 1.9 2012/04/17 22:52:48 dmitriy Exp $
   make file used for "generic" project
   Copyright (c) 2004-2006 Dmitriy Rogatkin    -->

<bee name="project name" type="project">
  &env;

  <expression variable="javac">
     <operator name="append">
        <value variable="JAVA_HOME"/>
        <value>/bin/javac</value>
     </operator>
  </expression>

  <target name="check build" dir=".">
     <dependency>
        <expression>
          <operator name="eq">
            <function name ="timestamp">
               <parameter value="&build_directory;"/>
            </function>
            <value></value>
          </operator>
        </expression>
     </dependency>
     <block>
       <function name="mkd">
         <parameter value="&build_directory;"/>
       </function>
     </block>
  </target>

  <expression variable="java sources">
        <function name="newerwithdependency">
           <parameter value="&source_directory;/&domain;/.java"/>
           <parameter value="&build_directory;/&domain;/.class"/>
	   <parameter/>
	   <parameter value="&domain;"/>
        </function>
  </expression>

  <expression variable="class path">
     <operator name="append">
        <value variable="PROJECT_HOME"/>
        <value>/&build_directory;</value>
        <value variable="PATH SEPARATOR"/>
        <value variable="CUSTOM CP"/>
     </operator>
  </expression>

  <expression variable="compiler classes">
     <operator name="append">
        <value variable="JAVA_HOME"/>
        <value>/lib/tools.jar</value>
     </operator>
  </expression>

  <target name="compile" dir="PROJECT_HOME">
    <dependency target="check build"/>
    <dependency variable="java sources"/>
    <echo>Compiling...</echo>
    <task name="compile task" code="com.sun.tools.javac.Main" path="compiler classes">
       <parameter value="-classpath"/>
       <parameter variable="class path"/>
       <parameter value="-source"/>
       <parameter value="1.5"/>
       <parameter value="-d"/>
       <parameter value="&build_directory;" type="dir"/>
       <parameter variable="java sources"/>>
      <onexit>
        <if>
          <expression>
             <operator name="neq"><value variable="resultcode"/><value>0</value></operator>
          </expression>
          <block type="then">
                 <echo>Error(s) at compilation</echo>
                 <function name="stop">
			<parameter value="1"/>
                 </function>
          </block>
       </if>
      </onexit>
      <!--onexception>
	<block>
                 <echo>Exception at compilation</echo>
                 <function name="stop">
			<parameter value="-1"/>
                 </function>
	</block>
      </onexception-->
    </task>
  </target>

  <expression variable="manifest file">
     <value type="path">&manifestf;</value>
  </expression>

  <target name="jar" dir="PROJECT_HOME">
    <echo>Jarring...</echo>
    <dependency target="compile"/>
    <dependency>
           <function name="allnewer">
              <parameter value="&build_directory;/&domain;" type="dir"/>
              <parameter value="&build_directory;/&build_file;" type="file"/>
           </function>
    </dependency>
    <dependency>
           <function name="allnewer">
              <parameter value="bee.xml" type="dir"/>
              <parameter value="&build_directory;/&build_file;" type="file"/>
           </function>
    </dependency>

    <task name="jar_do" code="sun.tools.jar.Main">
       <parameter>
          <expression>
            <if>
              <expression>
                <operator name="eq">
                  <value/>
                  <value variable="manifest file"/>
                </operator>
              </expression>
              <block type="then">
                <value>-cf</value>
              </block>
              <block type="else">
                <operator name="array">
	           <value>-cmf</value>
                   <value variable="manifest file"/>
                 </operator>
              </block>
            </if>
          </expression>
       </parameter>   
       <parameter value="&build_directory;/&build_file;" type="file"/>
       <parameter value="-C"/>
       <parameter value="&build_directory;" type="dir"/>
       <parameter value="&domain;" type="dir"/>
      <onexception>
	<block>
                 <echo>Exception at jarring</echo>
                 <function name="stop">
			<parameter value="-1"/>
                 </function>
	</block>
      </onexception>
    </task>
  </target>

  <target name="clean" dir="PROJECT_HOME">
    <dependency>
       <expression>
         <operator name="eq">
            <value>y</value>  
            <function name="ask">
               <parameter value="Are you sure to remove all files in &build_directory; [n]?"/>
               <parameter value="n"/>
            </function>
        </operator>
      </expression>
    </dependency>
    <block>
      <echo>Cleaning...</echo>
      <function name="rm">
         <parameter value="&build_directory;/*/*/*/*/*.class" type="path"/>
         <parameter value="&build_directory;/&build_file;" type="file"/>
      </function>
    </block>
  </target>

  <expression variable="run class path">
     <operator name="append">
        <value variable="PROJECT_HOME"/>
        <value>/&build_directory;/&build_file;</value>
        <value variable="PATH SEPARATOR"/>
     </operator>
  </expression>

  <target name="run" dir="PROJECT_HOME">
    <echo>Running...</echo>
    <dependency target="jar"/>
    <dependency value="true"/>
    <task name="main" code="&main_class;" path="run class path">
       <parameter variable="~#args#~"/>
    </task>
  </target>  
</bee>

=== drogatkin/7Bee/examples/jspapi/bee.xml
<?xml version="1.0" encoding="utf-8"?>
 <!DOCTYPE bee PUBLIC "-//Dmitriy Rogatkin//DTD Bee Project Builder 1.0//EN"
    "http://7bee.j2ee.us/xml/DTD/bee.dtd" [
      <!ENTITY env SYSTEM "./env.xml">
      <!ENTITY build_directory "lib">
      <!ENTITY jarname "jsp">
      ]>
<!-- $Id: bee.xml,v 1.2 2006/06/24 22:40:17 rogatkin Exp $
   make file used J2EE
   Copyright (c) 2006 Dmitriy Rogatkin    -->

<bee name="jsp" type="project">
  &env;

  <echo>JSP API building...</echo>
                     	
  <expression variable="compiler classes">
     <operator name="append">
        <value variable="JAVA_HOME"/>
        <value>/lib/tools.jar</value>
     </operator>
  </expression>

  <target name="check lib" dir=".">
     <dependency>
        <expression>
          <operator name="eq">
            <function name ="timestamp">
               <parameter value="&build_directory;"/>
            </function>
            <value/>
          </operator>
        </expression>
     </dependency>
     <task exec="mkdir">
       <parameter value="&build_directory;"/>
     </task>
  </target>

  <expression variable="api sources">
        <function name="newerwithdependency">
           <parameter value="src\share\.java"/>
           <parameter value="&build_directory;\.class"/>
           <parameter value=""/>
           <parameter/>
        </function>
  </expression>

  <expression variable="class path">
    <operator name="append">
       <value>&build_directory;</value>
       <value variable="PATH SEPARATOR"/>
       <value variable="SERVLET_HOME"/>
       <value>/servlet.jar</value>
    </operator>
  </expression>


  <target name="compile" dir="JSP_HOME">
    <dependency target="check lib"/>
    <dependency variable="api sources"/>
    <task name="main" code="com.sun.tools.javac.Main" path="compiler classes">
       <parameter value="-classpath"/>
       <parameter variable="class path"/>
       <parameter value="-d"/>
       <parameter value="&build_directory;" type="dir"/>
       <parameter value="-source"/>
       <parameter value="1.4"/>
       <parameter value="-sourcepath"/>
       <parameter value="src\share" type="dir"/>
       <parameter variable="api sources"/>
      <onexit>
        <if>
          <expression>
             <operator name="neq"><value variable="resultcode"/><value>0</value></operator>
          </expression>
          <block type="then">
                 <echo>Error(s) at compilation</echo>
                 <function name="stop">
			<parameter value="1"/>
                 </function>
          </block>
       </if>
      </onexit>
    </task>
  </target>

  <expression variable="resource list">
           <function name="cropname">
              <parameter value="src\share\javax\servlet\jsp\tagext\doc-files\*.gif"/>
              <parameter value="src\\share\\"/>
           </function>
  </expression>

  <target name="copy resources">
     <block>
         <function name="cp">
             <parameter>src/share/dtd/jsp*.dtd</parameter>
             <parameter>&build_directory;/javax/servlet/jsp/resources</parameter>
             <parameter>src/share/dtd/jsp*.xsd</parameter>
             <parameter>&build_directory;/javax/servlet/jsp/resources</parameter>
             <parameter>src/share/dtd/web-jsp*.dtd</parameter>
             <parameter>&build_directory;/javax/servlet/jsp/resources</parameter>
             <parameter>src/share/dtd/web-jsp*.xsd</parameter>
             <parameter>&build_directory;/javax/servlet/jsp/resources</parameter>
         </function>
     </block>
  </target>

  <target name="jar" dir=".">
    <dependency target="compile"/>
    <dependency target="copy resources"/>
    <dependency>
           <function name="allnewer">
              <parameter value="&build_directory;\" type="dir"/>
              <parameter value="&jarname;.jar" type="file"/>
           </function>
    </dependency>
    <dependency>
           <function name="allnewer">
              <parameter value="bee.xml" type="dir"/>
              <parameter value="&jarname;.jar" type="file"/>
           </function>
    </dependency>
    <task name="jar_do" code="sun.tools.jar.Main">
       <parameter value="-cmf"/>
       <parameter value="src\etc\manifest"/>
       <parameter value="&jarname;.jar" type="file"/>
       <parameter value="-C"/>
       <parameter value="&build_directory;" type="dir"/>
       <parameter value="." type="dir"/>
       <parameter>
            <expression variable="resources">
              <variable name="resources"/>
              <for variable="resource name" in="resource list">
                  <operator name="array" variable="resources">
                      <value variable="resources"/>
                      <value>-C</value>
                      <value>src\share</value>
                      <value variable="resource name"/>
                  </operator>
               </for>
            </expression>
       </parameter>
    </task>
  </target>
</bee>

=== drogatkin/7Bee/examples/lame/bee.xml
<?xml version="1.0" encoding="utf-8"?>
 <!DOCTYPE bee PUBLIC "-//Dmitriy Rogatkin//DTD Bee Project Builder 1.0//EN"
    "http://7bee.j2ee.us/xml/DTD/bee.dtd">
<!-- $Id: bee.xml,v 1.1 2006/12/14 06:28:34 rogatkin Exp $
   lame launcher
   Copyright (c) Dmitriy Rogatkin    -->

<bee name="lame" type="project">

  <variable  name="wav files" value="*.wav" type="file"/>
  <target name="run_lame" dir=".">
    <for variable="wav file" in="wav files">
       <echo variable="wav file"/>
       <expression name="pure name">
         <function name="filename">
            <parameter variable="wav file"/>
         </function>
       </expression>
       <task exec="lame">
          <parameter>-h</parameter>
          <parameter>-V1</parameter>
          <parameter>
             <operator name="append">
               <value variable="pure name"/>
               <value>.wav</value>
             </operator>
          </parameter>
          <parameter>
             <operator name="append">
               <value variable="pure name"/>
               <value>.mp3</value>
             </operator>
          </parameter>
       </task>
    </for>
  </target>
</bee>

=== drogatkin/7Bee/examples/arbat/bee-all.xml
<?xml version="1.0" encoding="utf-8"?>
 <!DOCTYPE bee PUBLIC "-//Dmitriy Rogatkin//DTD Bee Project Builder 1.0//EN"
    "http://7bee.j2ee.us/xml/DTD/bee.dtd" [
      <!ENTITY env SYSTEM "./env.xml">
      ]>
<!-- $Id: bee-all.xml,v 1.7 2007/01/05 04:46:09 rogatkin Exp $
   make file used for Arbat project
   Copyright (c) Dmitriy Rogatkin    -->

<bee name="arbat" type="project">
  &env;

  <expression  variable="idl compiler">     
     <operator name="append">
        <value variable="JAVA_HOME"/>
        <value>/bin/idlj</value>
     </operator>
  </expression>

  <expression  variable="idl.timestamp">
     <operator name="append">
        <value variable="ARBAT_HOME"/>
        <value>/src/idl/.idl.touch</value>
     </operator>
  </expression>

  <expression  variable="include_lib">
     <operator name="append">
        <value variable="JAVA_HOME"/>
        <value>/lib</value>
     </operator>
  </expression>

  <expression  variable="common_src">
     <operator name="append">
        <value variable="ARBAT_HOME"/>
        <value>/src/java/common</value>
     </operator>
  </expression>

  <expression variable="idl_timestamp">
     <operator name="lt">
       <function name="timestamp">
          <parameter variable="idl.timestamp"/>
       </function>
       <function name="now"/>
     </operator>
  </expression>

  <variable name="old compatible"/>

  <block>
    <if>
       <expression>
         <operator name="eq">
           <value variable="orb_type"/>
           <value>boa</value>
         </operator>
       </expression>
       <block type="then">
          <variable name="old compatible">-oldImplBase</variable>
          <variable name="boa_orb">true</variable>
       </block>
       <block type="else">
          <variable name="old compatible"/>
          <variable name="boa_orb">false</variable>
       </block>
    </if>
  </block>

  <echo variable="old compatible"/>
  <echo variable="idl_timestamp"/>

  <variable name="idl files" type="file">*.idl</variable>  

  <expression  variable="IDL src" type="dir">
     <operator name="append">
        <value variable="ARBAT_HOME"/>
        <value>/src/idl</value>
     </operator>
  </expression>

  <expression  variable="Java src common" type="dir">
     <operator name="append">
        <value variable="ARBAT_HOME"/>
        <value>/src/java/common</value>
     </operator>
  </expression>

  <expression variable="version src">
     <operator name="append">
        <value>src/java/</value>
        <value variable="java version"/>
        <value>\</value>
        <value variable="orb_type"/>
        <value>\.java</value>
     </operator>
  </expression>

  
  <expression  variable="impl java sources" >
           <function name="newerthan">
              <parameter variable="version src" type="dir"/>
              <parameter value="lib/.class" type="dir"/>
           </function>
  </expression>

  <expression  variable="java sources" >
           <function name="newerthan">
              <parameter variable="src/common/.java" type="dir"/>
              <parameter value="lib/.class" type="dir"/>
           </function>
  </expression>


  <variable name="event, naming IDLs" type="array">CosEventChannelAdmin.idl CosEventComm.idl CosNaming.idl</variable>
<!-- java com.sun.tools.corba.se.idl.toJavaPortable.Compile [options] <idl file> -->
  <target name="idl" dir="IDL src">
    <dependency variable="idl_timestamp"/>
    <echo>Idl compilation...</echo>
    <for variable="idl file" in="event, naming IDLs">
      <task name="idl compilation" exec="idl compiler">
         <parameter variable="old compatible"/>
         <parameter value="-i"/>
         <parameter variable="include_lib"/>
         <parameter value="-i"/>
         <parameter variable="common_src"/>
         <parameter value="-keep"/>
         <parameter value="-fall"/>
         <parameter value="-td"/>
         <parameter variable="Java src common"/>
         <parameter variable="packages list">
            <expression variable="packages list">
              <variable name="packages list"/>
              <for variable="package name" in="event, naming IDLs">
                  <operator name="array" variable="packages list">
                      <value variable="packages list"/>
                      <value>-pkgPrefix</value>
                      <function name="filename">
                         <parameter variable="package name"/>
                      </function>
                      <value>org.omg</value>
                  </operator>
               </for>
            </expression>
         </parameter>
         <parameter variable="idl file"/>
         <onexit>
            <if>
              <expression>
                 <operator name="neq"><value variable="resultcode"/><value>0</value></operator>
              </expression>
              <block type="then">
                 <echo>Error in IDL</echo>
                 <function name="stop">
			<parameter value="1"/>
                 </function>
              </block>
              <block type="else">
                  <function name="write">
                     <parameter variable="idl.timestamp"/>
                     <parameter value=""/>
                  </function>
                <!--task name="set time stamp" exec="touch">
                  <parameter variable="idl.timestamp"/>
                </task-->
              </block>
            </if>
        </onexit>
      </task>
    </for>
<!-- TODO: find out why task here can be proceeded if previous failed -->
  </target>

  <variable name="class path"/>

  <expression variable="target version options">
     <if>
        <expression>
          <operator name="lt">
               <value variable="java version"/>
               <value value="1.5"/>
          </operator>
        </expression>
        <block type="then">
            <expression variable="class path">
               <operator name="append">
                   <value variable="ARBAT_HOME"/>
                   <value>/lib</value>
                   <value variable="PATH SEPARATOR"/>
                   <value></value>
                   <value variable="ARBAT_HOME"/>
                   <value>/jsr166/lib/backport-util-concurrent.jar</value>
               </operator>
            </expression>
            <operator name="array">
               <value>-target</value>
               <value variable="java version"/>
               <value>-bootclasspath</value>
               <value variable="target runtime"/>
            </operator>
        </block>
        <block type="else">
            <expression variable="class path">
               <operator name="append">
                   <value variable="ARBAT_HOME"/>
                   <value>/lib</value>
               </operator>
            </expression>
            <expression>
            </expression>
        </block>
     </if>
  </expression>


  <expression  variable="java compiler">
     <operator name="append">
        <value variable="JAVA_HOME"/>
        <value>/bin/javac</value>
     </operator>
  </expression>

  <target name="java" dir="ARBAT_HOME" >

    <dependency target="idl"/>
    <dependency>
      <expression>
        <operator name="or">
           <value variable="java sources"/>
	   <value variable="impl java sources"/>
        </operator>
      </expression>
    </dependency>
    <echo variable="impl java sources"/>
    <echo variable="java sources"/>
    <task name="java compilation" exec="java compiler">
       <parameter value="-source"/>
       <parameter variable="java version"/>
       <parameter variable="target version options"/>
       <parameter value="-classpath"/>
       <parameter variable="class path"/>
       <parameter value="-d"/>
       <parameter value="lib" type="dir"/>
       <parameter value="-sourcepath"/>
       <parameter value="src/java/common" type="dir"/>
       <parameter variable="java sources"/>
       <parameter variable="impl java sources"/>
        <onexit>
           <if>
             <expression>
                <operator name="neq"><value variable="resultcode"/><value>0</value></operator>
             </expression>
             <block type="then">
                <echo>Error in compilation</echo>
                <function name="stop">
	            <parameter value="1"/>
                </function>
             </block>
           </if>
        </onexit>
    </task>
  </target>

  <target name="clear" dir="ARBAT_HOME">
    <block>
       <echo>Clear..</echo>
       <function name="rm">
         <parameter value="src/idl/.idl.touch" type ="path"/>
         <parameter value="lib/*/*/*/*/*.class"/>
         <parameter value="src/java/common/org/omg/*/*/*.java"/>        
         <parameter value="lib/arbat.jar"/>
       </function>
    </block>
  </target>

  <target name="jar" dir="ARBAT_HOME">
    <dependency target="java"/>
    <dependency>
           <function name="allnewer">
              <parameter value="src/java/common/" type="dir"/>
              <parameter value="lib/arbat.jar" type="file"/>
           </function>
    </dependency>
    <dependency>
           <function name="allnewer">
              <parameter value="bee-all.xml" type="file"/>
              <parameter value="lib/arbat.jar" type="file"/>
           </function>
    </dependency>
    <task name="jar_do" code="sun.tools.jar.Main">
       <parameter value="-cf"/>
       <parameter value="lib/arbat.jar" type="file"/>
       <parameter value="-C"/>
       <parameter value="lib" type="dir"/>
       <parameter value="org"/>
       <parameter value="-C"/>
       <parameter value="src/configuration"/>
       <parameter value="resource/configuration.properties"/>
    </task>
  </target>
</bee>

=== drogatkin/7Bee/examples/template/bee-template.xml
<?xml version="1.0" encoding="utf-8"?>
 <!DOCTYPE bee PUBLIC "-//Dmitriy Rogatkin//DTD Bee Project Builder 1.0//EN"
    "https://raw.githubusercontent.com/drogatkin/7Bee/master/bee.dtd" >
<!-- 
   Unzip
   Copyright (c) Dmitriy Rogatkin    -->

<bee name="template" type="project">
	<variable name="fam" value="Cherish"/>
	<variable name="sign">Haliava</variable>
  <target name="test" dir=".">
     <block>
         <variable name="name" value="Gosha"/>
         <echo>Hey ${name}!</echo>
         <echo>When ${name}, you visit us ${fam}?</echo>
         <echo>Yours ${sign}</echo>
     </block>
  </target>
</bee>
