=== drogatkin/7Bee/bee.dtd
<!-- $Id: bee.dtd,v 1.34 2011/06/28 23:23:36 dmitriy Exp $
  project Bee, DTD file of bee make files 
  Copyright (c) 2004 Dmitriy Rogatkin   -->

<!ENTITY % PROJ_TYPE "build|test|run">

<!ENTITY % VAR_TYPE "variable|file|directory|url|number|date|array|path|environment|property">
<!ENTITY % BLOCK_TYPE "then|else|case">
<!ENTITY % YES_NO "yes|no">

<!ELEMENT bee (variable|expression|block|target+)*>
<!ATTLIST bee
         name    CDATA #REQUIRED
         dir     CDATA #IMPLIED
         type    (%PROJ_TYPE;) "build"
>

<!ELEMENT variable (#PCDATA)>

<!ATTLIST variable
         name    CDATA #REQUIRED
         type (%VAR_TYPE;) #IMPLIED
>

<!ELEMENT expression (operator|for|function|if|switch)>
<!-- name - the result expression is stored
     variable - alias of name -->
<!ATTLIST expression
         name    CDATA #REQUIRED
         variable CDATA #IMPLIED
>

<!ELEMENT operator (value|function|variable|expression|operator)*>
<!ATTLIST operator
         name    CDATA #REQUIRED
         type (%VAR_TYPE;) #IMPLIED
>

<!ELEMENT value (#PCDATA)>
<!ATTLIST value
         name CDATA        #IMPLIED
         type (%VAR_TYPE;) #IMPLIED
         variable CDATA    #IMPLIED
         property CDATA    #IMPLIED
>

<!ELEMENT function (parameter*)>
<!ATTLIST function
         name    CDATA #REQUIRED
>

<!ELEMENT parameter (#PCDATA|expression|function|operator)*>
<!ATTLIST parameter
         name    CDATA #IMPLIED
         variable CDATA #IMPLIED
         value CDATA #IMPLIED
         type (%VAR_TYPE;) #IMPLIED
>

<!ELEMENT target (dependency*, (block|task)*, echo*)>
<!ATTLIST target
         name CDATA #REQUIRED
         dir CDATA #IMPLIED
         comment CDATA #IMPLIED
>

<!ELEMENT echo (#PCDATA)>
<!-- attribute options is similar to options for Unix echo
       -n     do not output the trailing newline
       -e     enable interpretation of the backslash-escaped characters listed below
       -E     disable interpretation of those sequences in STRINGs
       Without -E, the following sequences are recognized and interpolated:
       \NNN   the character whose ASCII code is NNN (octal)
       \\     backslash
       \a     alert (BEL)
       \b     backspace
       \c     suppress trailing newline
       \f     form feed
       \n     new line
       \r     carriage return
       \t     horizontal tab
       \v     vertical tab
-->
<!ATTLIST echo
         variable CDATA        #IMPLIED
         name     CDATA        #IMPLIED
         type     (%VAR_TYPE;) #IMPLIED
         options  CDATA        #IMPLIED
>

<!ELEMENT for (task|operator|expression|block|interrupt|if)*>
<!ATTLIST for
         variable CDATA #REQUIRED
         in CDATA #REQUIRED 
         separator CDATA #IMPLIED
>

<!ELEMENT task (parameter*, (onexit?,onexception?))>

<!ATTLIST task
         name  CDATA #REQUIRED
         code  CDATA #IMPLIED
         exec  CDATA #IMPLIED
         path  CDATA #IMPLIED
         dir   CDATA #IMPLIED
         stdout CDATA #IMPLIED
         stdin CDATA #IMPLIED
         errout CDATA #IMPLIED
>

<!ELEMENT onexit (if)>

<!ELEMENT onexception (block)>

<!ELEMENT if (expression, (then|block), (else|block)?)>

<!ELEMENT then (task|function|expression|echo|if|for|switch|interrupt)*>

<!ELEMENT else (task|function|expression|echo|if|for|switch|interrupt)*>

<!ELEMENT block (task|function|expression|echo|if|for|switch|interrupt)*>
<!ATTLIST block
          name CDATA #IMPLIED
          variable CDATA #IMPLIED
          value CDATA #IMPLIED
          type (%BLOCK_TYPE;) #IMPLIED
>

<!ELEMENT switch (expression, (block)*)>
<!ATTLIST switch
          name CDATA #IMPLIED
          variable CDATA #IMPLIED
>

<!ELEMENT dependency (#PCDATA|expression|function|operator)*>
<!-- name - variable name where result of dependency calculation stored
     target - target of dependency
     variable - name of variable it depend on, can be boolean
-->
<!ATTLIST dependency
          name CDATA #IMPLIED
          target CDATA #IMPLIED
          variable CDATA #IMPLIED
          process_only (%YES_NO;) "no" 
>

<!ELEMENT interrupt (empty)>
<!-- name - can be a name of named block to unterrupt 
-->
<!ATTLIST interrupt
          name CDATA #IMPLIED
>

=== drogatkin/7Bee/examples/az/bee.xml
<?xml version="1.0" encoding="utf-8"?>
 <!DOCTYPE bee PUBLIC "-//Dmitriy Rogatkin//DTD Bee Project Builder 1.0//EN"
    "http://7bee.j2ee.us/xml/DTD/bee.dtd" [
      <!ENTITY env SYSTEM "./env.xml">
      <!ENTITY build_directory "build">
      <!ENTITY build_file "az.jar">
      <!ENTITY domain "">
      <!ENTITY manifestf "">
      <!ENTITY main_class "org.gudy.azureus2.ui.swt.Main">
      ]>
<!-- $Id: bee.xml,v 1.2 2005/11/02 21:31:26 rogatkin Exp $
   make file used for "generic" project
   Copyright (c) 2004 Dmitriy Rogatkin    -->

<bee name="project name" type="project">
  &env;

  <expression variable="javac">
     <operator name="append">
        <value variable="JAVA_HOME"/>
        <value>/bin/javac</value>
     </operator>
  </expression>

  <target name="check build" dir=".">
     <dependency>
        <expression>
          <operator name="eq">
            <function name ="timestamp">
               <parameter value="&build_directory;"/>
            </function>
            <value></value>
          </operator>
        </expression>
     </dependency>
     <task exec="mkdir">
       <parameter value="&build_directory;"/>
     </task>
  </target>

  <expression variable="java sources">
        <function name="newerwithdependency">
           <parameter value="src\&domain;\.java"/>
           <parameter value="&build_directory;\&domain;\.class"/>
	   <parameter/>
	   <parameter value="&domain;"/>
        </function>
  </expression>

  <expression variable="class path">
     <operator name="append">
        <value variable="PROJECT_HOME"/>
        <value>/&build_directory;</value>
        <value variable="PATH SEPARATOR"/>
        <value variable="CUSTOM CP"/>
     </operator>
  </expression>

  <expression variable="compiler classes">
     <operator name="append">
        <value variable="JAVA_HOME"/>
        <value>/lib/tools.jar</value>
     </operator>
  </expression>

  <target name="compile" dir="PROJECT_HOME">
    <dependency target="check build"/>
    <dependency variable="java sources"/>
    <echo>Compiling...</echo>
    <task name="main" code="com.sun.tools.javac.Main" path="compiler classes">
       <parameter value="-classpath"/>
       <parameter variable="class path"/>
       <parameter value="-source"/>
       <parameter value="1.5"/>
       <parameter value="-d"/>
       <parameter value="&build_directory;" type="dir"/>
       <parameter variable="java sources"/>>
      <onexit>
        <if>
          <expression>
             <operator name="neq"><value variable="resultcode"/><value>0</value></operator>
          </expression>
          <block type="then">
                 <echo>Error(s) at compilation</echo>
                 <function name="stop">
			<parameter value="1"/>
                 </function>
          </block>
       </if>
      </onexit>
      <!--onexception>
	<block>
                 <echo>Exception at compilation</echo>
                 <function name="stop">
			<parameter value="-1"/>
                 </function>
	</block>
      </onexception-->
    </task>
  </target>

  <expression variable="manifest file">
     <value type="path">&manifestf;</value>
  </expression>

  <target name="jar" dir="PROJECT_HOME">
    <echo>Jarring...</echo>
    <dependency target="compile"/>
    <dependency>
           <function name="allnewer">
              <parameter value="&build_directory;/&domain;" type="dir"/>
              <parameter value="&build_directory;/&build_file;" type="file"/>
           </function>
    </dependency>
    <dependency>
           <function name="allnewer">
              <parameter value="bee.xml" type="dir"/>
              <parameter value="&build_directory;/&build_file;" type="file"/>
           </function>
    </dependency>

    <task name="jar_do" code="sun.tools.jar.Main">
       <parameter>
          <expression>
            <if>
              <expression>
                <operator name="eq">
                  <value/>
                  <value variable="manifest file"/>
                </operator>
              </expression>
              <block type="then">
                <value>-cf</value>
              </block>
              <block type="else">
                <operator name="array">
	           <value>-cmf</value>
                   <value variable="manifest file"/>
                 </operator>
              </block>
            </if>
          </expression>
       </parameter>   
       <parameter value="&build_directory;/&build_file;" type="file"/>
       <parameter value="-C"/>
       <parameter value="&build_directory;" type="dir"/>
       <parameter value="&domain;" type="dir"/>
       <parameter value="-C"/>
       <parameter value="src"/>
       <parameter value="org/gudy/azureus2/ui/splash/azureus.jpg"/>
       <parameter value="-C"/>
       <parameter value="src"/>
       <parameter value="org/gudy/azureus2/ui/icons"/>
       <parameter value="-C"/>
       <parameter value="src"/>
       <parameter value="org\gudy\azureus2\internat"/>
      <onexception>
	<block>
                 <echo>Exception at jarring</echo>
                 <function name="stop">
			<parameter value="-1"/>
                 </function>
	</block>
      </onexception>
    </task>
  </target>

  <target name="clean" dir="PROJECT_HOME">
    <dependency>
       <expression>
         <operator name="eq">
            <value>y</value>  
            <function name="ask">
               <parameter value="Are you sure to remove all files in &build_directory; [n]?"/>
               <parameter value="n"/>
            </function>
        </operator>
      </expression>
    </dependency>
    <block>
      <echo>Cleaning...</echo>
      <function name="rm">
         <parameter value="&build_directory;/*/*/*/*/*.class" type="dir"/>
         <parameter value="&build_directory;/&build_file;" type="file"/>
      </function>
    </block>
  </target>

  <expression variable="run class path">
     <operator name="append">
        <value variable="PROJECT_HOME"/>
        <value>/&build_directory;/&build_file;</value>
        <value variable="PATH SEPARATOR"/>
        <value>C:\Work Files\swt\build\swt.jar</value>
     </operator>
  </expression>

  <target name="run" dir="PROJECT_HOME">
    <echo>Running...</echo>
    <dependency target="jar"/>
    <dependency value="true"/>
    <task name="main" code="&main_class;" path="run class path">
       <parameter name="java.library.path">C:\Work Files\swt</parameter>
       <parameter variable="~#args#~"/>
    </task>
  </target>  
</bee>

=== drogatkin/7Bee/examples/mindterm/bee.xml
<?xml version="1.0" encoding="utf-8"?>
 <!DOCTYPE bee PUBLIC "-//Dmitriy Rogatkin//DTD Bee Project Builder 1.0//EN"
    "http://7bee.j2ee.us/xml/DTD/bee.dtd" [
      <!ENTITY env SYSTEM "./env.xml">
      ]>
<!-- $Id: bee.xml,v 1.6 2006/02/28 08:56:28 rogatkin Exp $
   make file used for Mindterm project
   Copyright (c) Dmitriy Rogatkin    -->

<bee name="mindterm 3.0.1" type="project">
  &env;

  <echo>Mindterm project building...</echo>

  <expression variable="javac">
     <operator name="append">
        <value variable="JAVA_HOME"/>
        <value>/bin/javac</value>
     </operator>
  </expression>

  <expression variable="tools">
     <operator name="append">
        <value variable="JAVA_HOME"/>
        <value>/lib/tools.jar</value>
     </operator>
  </expression>

  <target name="init">
     <dependency>
        <expression>
          <operator name="eq">
            <function name ="timestamp">
               <parameter value="build"/>
            </function>
            <value/>
          </operator>
        </expression>
     </dependency>
     <task exec="mkdir">
       <parameter value="build"/>
     </task>
     <task exec="mkdir">
       <parameter value="build\mindterm"/>
     </task>
  </target>


  <target name="manifest" dir="MT_HOME">
    <block>
       <function name="write">
         <parameter value="manifest.mf" type="file"/>
         <parameter>Manifest-Version: 1.0
Name: MindTerm.jar
Main-Class: com.mindbright.application.MindTerm
Java-Bean: False</parameter>
       </function>
    </block>
  </target>

  <expression variable="java sources">
     <operator name="array">
        <function name="newerwithdependency">
           <parameter value="com\.java"/>
           <parameter value="build\com\.class"/>
           <parameter value=""/>
        </function>
        <function name="newerwithdependency">
           <parameter value="netscape\.java"/>
           <parameter value="build\netscape\.class"/>
           <parameter value=""/>
        </function>
    </operator>         
  </expression>

  <target name="compile" dir="MT_HOME">
    <dependency target="init"/>
    <dependency variable="java sources"/>
    <dependency>
           <function name="allnewer">
              <parameter value="bee.xml" type="file"/>
              <parameter value=".\" type="dir"/>
           </function>
    </dependency>
    <task name="main" code="com.sun.tools.javac.Main" path="tools">
       <parameter value="-classpath"/>
       <parameter variable="build"/>
       <parameter value="-d"/>
       <parameter value="build" type="dir"/>
       <parameter value="-source"/>
       <parameter value="1.4"/>
       <parameter value="-target"/>
       <parameter value="1.4"/>
       <parameter value="-sourcepath"/>
       <parameter value="." type="dir"/>
       <parameter variable="java sources"/>
      <onexit>
        <if>
          <expression>
             <operator name="neq"><value variable="resultcode"/><value>0</value></operator>
          </expression>
          <block type="then">
                 <echo>Error(s) at compilation</echo>
                 <function name="stop">
			<parameter value="1"/>
                 </function>
          </block>
       </if>
      </onexit>
    </task>
  </target>

  <target name="jar" dir="BEE_HOME">
    <dependency target="compile"/>
    <dependency target="manifest"/>
    <dependency>
           <function name="allnewer">
              <parameter value="build\" type="dir"/>
              <parameter value="build\mindterm\mindterm.jar" type="file"/>
           </function>
    </dependency>
    <task name="jar_do" code="sun.tools.jar.Main">
       <parameter value="-cmf"/>
       <parameter value="manifest.mf" type="file"/>
       <parameter value="build\mindterm\mindterm.jar" type="file"/>
       <parameter value="-C"/>
       <parameter value="build" type="dir"/>
       <parameter value="com"/>
       <parameter value="-C"/>
       <parameter value="build" type="dir"/>
       <parameter value="netscape"/>
       <parameter value="-C"/>
       <parameter value="." type="dir"/>
       <parameter value="defaults/"/>
    </task>
  </target>
</bee>

=== drogatkin/7Bee/examples/generic/bee-fx.xml
<?xml version="1.0" encoding="utf-8"?>
 <!DOCTYPE bee PUBLIC "-//Dmitriy Rogatkin//DTD Bee Project Builder 1.0//EN"
    "https://raw.githubusercontent.com/drogatkin/7Bee/master/bee.dtd" [
      <!ENTITY env SYSTEM "./env-fx.xml">
      <!ENTITY project "eboofx">    <!-- project name (valid for file names) -->
      <!ENTITY build_directory "bin">  <!-- project build directory -->
      <!ENTITY source_directory "src"> <!-- change if differs -->
      <!ENTITY doc_directory "doc"> <!-- change if differs -->
      <!ENTITY build_file "&project;.jar"> <!-- change if differs -->
      <!ENTITY domain "net">  <!-- change if differs -->
      <!ENTITY resources "&domain;.&project;.resources">
      <!ENTITY manifestf ""> <!-- type relative path to manifest -->
      <!ENTITY main_class "net.amsoft.eboofx.Main">  <!-- type main class for run -->
      ]>
<!-- $Id: bee-fx.xml,v 1.2 2012/03/02 04:09:36 dmitriy Exp $
   make file used for "generic" project
   Copyright (c) 2004-2009 Dmitriy Rogatkin    -->

<bee name="&project;" type="project">
  &env;

  <expression variable="javafxc">
     <operator name="append">
        <value variable="JAVAFX_HOME"/>
        <value>/bin/javafxc</value>
     </operator>
  </expression>

  <expression variable="runfx">
     <operator name="append">
        <value variable="JAVAFX_HOME"/>
        <value>/bin/javafx</value>
     </operator>
  </expression>

  <expression  variable="JavaDoc">     
     <operator name="append">
        <value variable="JAVAFX_HOME"/>
        <value>/bin/javadoc</value>
     </operator>
  </expression>

  <expression  variable="package">     
     <operator name="append">
        <value variable="JAVAFX_HOME"/>
        <value>/bin/javafxpackager</value>
     </operator>
  </expression>


  <target name="help">
     <echo>
     ******** &project; Build Process ********
* Available targets:                              *
*  doc      - build JavaDoc                       *
*  compile  - do Java compilation                 *
*  pack     - package                             *
*  test     - run application &main_class;        *
***************************************************
    </echo>
  </target>

  <target name="check build" dir="PROJECT_HOME">
     <dependency>
        <expression>
          <operator name="eq">
            <function name ="timestamp">
               <parameter value="&build_directory;"/>
            </function>
            <value></value>
          </operator>
        </expression>
     </dependency>
     <task exec="mkdir">
       <parameter value="&build_directory;"/>
     </task>
  </target>

  <target name="check doc" dir="PROJECT_HOME">
     <dependency>
        <expression>
          <operator name="eq">
            <function name ="timestamp">
               <parameter value="&doc_directory;"/>
            </function>
            <value></value>
          </operator>
        </expression>
     </dependency>
     <task exec="mkdir">
       <parameter value="&doc_directory;"/>
     </task>
  </target>

  <expression variable="src path">
      <operator name="append">
         <value type="dir">&source_directory;</value>
         <function name="cropname">
            <parameter value="/&domain;"/>
            <parameter value="\."/>
            <parameter value="/"/>
            <parameter value="a"/>
         </function>
      </operator>
  </expression>

  <expression>
    <for variable="n path" in="src path">
     <expression variable="src path">
       <operator name="append">
          <value variable="n path"/>
          <value>/.fx</value>
       </operator>
     </expression>
    </for>
  </expression>
 
  <expression variable="java sources">
        <function name="newerwithdependency">
           <parameter variable="src path"/>
           <parameter value="&build_directory;\&domain;\.class"/>
	   <parameter/>
	   <parameter value="&domain;"/>
        </function>
  </expression>

  <expression variable="class path">
     <operator name="append">
        <value variable="PROJECT_HOME"/>
        <value>/&build_directory;</value>
        <value variable="PATH SEPARATOR"/>
        <value variable="CUSTOM CP"/>
     </operator>
  </expression>

  <target name="compile" dir="PROJECT_HOME">
    <dependency target="check build"/>
    <dependency variable="java sources"/>
    <echo>Compiling...</echo>
    <task exec="javafxc">
       <parameter value="-classpath"/>
       <parameter variable="class path"/>
       <parameter value="-source"/>
       <parameter variable="comp target"/>
       <parameter value="-target"/>
       <parameter variable="comp target"/>
       <parameter value="-d"/>
       <parameter value="&build_directory;" type="dir"/>
       <parameter variable="java sources"/>>
      <onexit>
        <if>
          <expression>
             <operator name="neq"><value variable="resultcode"/><value>0</value></operator>
          </expression>
          <block type="then">
                 <echo>Error(s) at compilation</echo>
                 <function name="stop">
			<parameter value="1"/>
                 </function>
          </block>
       </if>
      </onexit>
      <onexception>
	<block>
                 <echo>Exception at compilation</echo>
                 <echo variable="~#error#~"/>
                 <function name="stop">
			<parameter value="-1"/>
                 </function>
	</block>
      </onexception>
    </task>
  </target>

  <expression variable="manifest file">
     <value type="path">&manifestf;</value>
  </expression>

  <target name="doc" dir="PROJECT_HOME">
    <dependency target="check doc"/>
    <dependency>true</dependency>
    <!--task name="JavaDoc" code="com.sun.tools.javadoc.Main" path="compiler classes"-->
    <task exec="JavaDoc">
      <!--parameter name="env.class.path" variable="compiler classes"/-->
      <parameter>-d</parameter>
      <parameter value="&doc_directory;"/>
      <parameter>-sourcepath</parameter>  
      <parameter value="&source_directory;"/>
      <parameter>-subpackages</parameter>
      <parameter>&domain;</parameter>
      <parameter>-classpath</parameter>  
      <parameter value="&build_directory;"/>
      <parameter>&domain;</parameter>
    </task>  
  </target>

  <target name="pack" dir="PROJECT_HOME">
    <echo>Packaging &project;...</echo>
    <dependency target="compile"/>
    <dependency>
           <function name="allnewer">
              <parameter value="&build_directory;/&domain;" type="dir"/>
              <parameter value="&build_directory;/&build_file;" type="file"/>
           </function>
    </dependency>
    <dependency>
           <function name="allnewer">
              <parameter value="bee.xml" type="dir"/>
              <parameter value="&build_directory;/&build_file;" type="file"/>
           </function>
    </dependency>

    <task name="pak_do" exec="package">
       <parameter>
          <expression>
            <if>
              <expression>
                <operator name="eq">
                  <value/>
                  <value variable="manifest file"/>
                </operator>
              </expression>
              <block type="then">
                <value>-cf</value>
              </block>
              <block type="else">
                <operator name="array">
	           <value>-cmf</value>
                   <value variable="manifest file"/>
                 </operator>
              </block>
            </if>
          </expression>
       </parameter>   
       <parameter value="&build_directory;/&build_file;" type="file"/>
       <parameter value="-C"/>
       <parameter value="&build_directory;" type="dir"/>
       <parameter value="&domain;" type="dir"/>
      <onexception>
	<block>
                 <echo>Exception at jarring</echo>
                 <function name="stop">
			<parameter value="-1"/>
                 </function>
	</block>
      </onexception>
    </task>
  </target>

  <target name="clean" dir="PROJECT_HOME">
    <dependency>
       <expression>
         <operator name="eq">
            <value>y</value>  
            <function name="ask">
               <parameter value="Are you sure to remove all files in &build_directory; [n]?"/>
               <parameter value="n"/>
            </function>
        </operator>
      </expression>
    </dependency>
    <block>
      <echo>Cleaning...</echo>
      <function name="rm">
         <parameter value="&build_directory;/*/*/*/*/*.class" type="path"/>
         <parameter value="&build_directory;/&build_file;" type="file"/>
      </function>
    </block>
  </target>

  <expression variable="run class path">
     <operator name="append">
        <value variable="PROJECT_HOME"/>
        <value>/&build_directory;/&build_file;</value>
        <value variable="PATH SEPARATOR"/>
        <value variable="CUSTOM CP"/>
     </operator>
  </expression>

  <target name="run" dir="PROJECT_HOME">
    <echo>Running...</echo>
    <dependency target="compile"/>
    <!--dependency target="pack"/-->
    <dependency value="true"/>
    <task name="main" exec="runfx">
       <parameter>-cp</parameter>
       <parameter>&build_directory;</parameter>
       <parameter>&main_class;</parameter>
       <parameter variable="~#args#~"/>
    </task>
  </target>  
</bee>

=== drogatkin/7Bee/examples/unzip/bee-unzip.xml
<?xml version="1.0" encoding="utf-8"?>
 <!DOCTYPE bee PUBLIC "-//Dmitriy Rogatkin//DTD Bee Project Builder 1.0//EN"
    "https://raw.githubusercontent.com/drogatkin/7Bee/master/bee.dtd" >
<!-- 
   Unzip
   Copyright (c) Dmitriy Rogatkin    -->

<bee name="unzip" type="project">

 
  <target name="unzip" dir=".">
     <block>
         <variable name="zip file"/>
         <for variable="current" in="~#args#~">
                <if>
                    <expression>
                        <operator name="eq">
                            <value variable="zip file"/>
                            <value/>
                        </operator>
                    </expression>
                    <then>
                        <expression name="zip file">
                            <value variable="current"/>
                        </expression>
                    </then>
                </if>
            </for>
         <function name="unzip">
            <parameter variable="zip file"/>
         </function>
     </block>
  </target>
</bee>

=== drogatkin/7Bee/examples/grepreplace/bee-root-rename.xml
<?xml version="1.0"?>
<!-- $Id: bee-root-rename.xml,v 1.1 2008/04/21 04:33:07 dmitriy Exp $ 
   Copyright 2008 MetricStream Inc.
   This script is used for for mass CVS root updates   -->
 <!DOCTYPE bee PUBLIC "-//Dmitriy Rogatkin//DTD Bee Project Builder 1.0//EN"
    "http://7bee.j2ee.us/xml/DTD/bee.dtd" [
      <!ENTITY replace_from "new ImageIcon\(">
      <!ENTITY replace_to "new ImageIconUrl\(">
  ]>

<bee name="Mass CVS root update script" type="project">
   <expression name="mask">
      <value value="*.java"/>
   </expression>
   <target name="mass update">
      <block>
               <expression name="root">
                 <value variable="mask" type="file"/>
               </expression>
               <!--echo variable="root"/-->
<!--- insert -->
                <for variable="file" in="root">
                   <block>
<echo variable="file"/>
                   <expression name="file cont">
                      <function name="read">
                        <parameter variable="file"/>
                        <parameter/>
                        <parameter/>
                      </function>
                   </expression>
<!--echo variable="file cont"/-->
                  <expression name="new content">
                       <function name="cropname">
                         <parameter variable="file cont"/>
                         <parameter>&replace_from;</parameter>
                         <parameter>&replace_to;</parameter>
                        <parameter>all</parameter>
                       </function>
                    </expression>
                    <expression name="content">
                      <for variable="line" in="new content">
                         <operator name="append">
                           <value variable="line"/>
                         </operator>
                      </for>
                    </expression>
                   <function name="write">
                     <parameter variable="file"/>
                     <parameter variable="content">
                      </parameter>
                   </function>>
                 </block>
               </for>
      </block>
   </target>
</bee>
